[package]
authors = ["Wadelma <delma@del.ma>"]
name = "darluca_lib"
version = "0.1.0"

[dependencies]
nom = "3.2.0"
failure = "0.1.1"
failure_derive = "0.1.1"
symtern = "0.1.0"
itertools = "0.7.4"
ena = "0.8.0"