[package]
name = "darluca"
version = "0.1.0"
authors = ["delma <delma@del.ma>"]

[dependencies]
libdarluca = {path = "../libdarluca"}
clap = "2.28.0"
nom = "3.2.0"
symtern = "0.1.0"
termcolor = "0.3"
failure = "0.1.1"
failure_derive = "0.1.1"